server:
  port: 9000

spring:
  application:
    name: iaam-service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true
        ddl-auto: none
        default_schema: users

  datasource:
    url: jdbc:postgresql://localhost:5432/iaam
    username: postgres
    password: pass

user:
  jwt:
    secret-key : 6C744C734F7978415A6D545151496B444166555A507549367A7A4A336263424A